### PR TITLE
X2 and river kilometers

### PR DESCRIPTION
**Pull request by rosehartman**
Hi Sam, I added some data with the river kilometer locations used for X2 and a larger file with all the river kilometer locations for the entire system. A lot of people might find it useful.

### CODE REVIEW

**Review by sbashevkin — CHANGES_REQUESTED** [review]
Thanks! I think it looks good, can you just knit the readme?

**Comment by sbashevkin** [comment]
Great, thank you. Have you looked into this error that came up when the data were plotted in the readme? Are the spatial data in some weird format? If so can they be transformed to the normal sf point type?

#> Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
#> give correct results for longitude/latitude data

**Comment by rosehartman** [comment]
Oh, right, I've seen that warning so many times i've started ignoring it. It happens pretty much any time you plot data from latitude/longitude data rather than UTMs. I suppose it's better to convert to the same CRS as the rest of the package, I can definitely do that.

**Comment by rosehartman** [comment]
OK, now i'm confused, I switched the CRS and its still giving that warning. I'll look into it later.

**Comment by rosehartman** [comment]
OK, I did some more research. 'geom_sf_text' has a note that for 'fun.geometry':  sf::st_point_on_surface(sf::st_zm(x)) will be used. Note that the function may warn about the incorrectness of the result if the data is not projected, but you can ignore this except when you really care about the exact locations.

There are no warnings when I just plot points, but if I plot text, it's basically a matter of the text not projecting across the map exactly accurately, and in this case I don't think i actually care about that. I just set the chunk options to 'warning = F' and it won't print the warning.

**Comment by sbashevkin** [comment]
OK great, thanks for looking into it!

**Review by sbashevkin — APPROVED** [review]

**Pull request merged**
